In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
kjv_csv = pd.read_csv('data/kjv.csv')
kjv_csv

,Verse ID,Book Name,Book Number,Chapter,Verse,Text
0,1,Genesis,1,1,1,¶ In the beginning God created the heaven and ...
1,2,Genesis,1,1,2,"And the earth was without form, and void; and ..."
2,3,Genesis,1,1,3,"¶ And God said, Let there be light: and there ..."
3,4,Genesis,1,1,4,"And God saw the light, that [it was] good: and..."
4,5,Genesis,1,1,5,"And God called the light Day, and the darkness..."
...,...,...,...,...,...,...
31097,31098,Revelation,66,22,17,"And the Spirit and the bride say, Come. And le..."
31098,31099,Revelation,66,22,18,For I testify unto every man that heareth the ...
31099,31100,Revelation,66,22,19,And if any man shall take away from the words ...
31100,31101,Revelation,66,22,20,"¶ He which testifieth these things saith, ‹Sur..."
31101,31102,Revelation,66,22,21,The grace of our Lord Jesus Christ [be] with y...

In [4]:
symbol = kjv_csv['Text'][0][0]
symbol

'¶'

In [5]:
patt = r"[^\w,;:'()\s.!?]"
cleaned_csv = kjv_csv['Text'].str.replace(patt, '', regex=True)
cleaned_kjv = kjv_csv.assign(cleaned=cleaned_csv)
cleaned_kjv

,Verse ID,Book Name,Book Number,Chapter,Verse,Text,cleaned
0,1,Genesis,1,1,1,¶ In the beginning God created the heaven and ...,In the beginning God created the heaven and t...
1,2,Genesis,1,1,2,"And the earth was without form, and void; and ...","And the earth was without form, and void; and ..."
2,3,Genesis,1,1,3,"¶ And God said, Let there be light: and there ...","And God said, Let there be light: and there w..."
3,4,Genesis,1,1,4,"And God saw the light, that [it was] good: and...","And God saw the light, that it was good: and G..."
4,5,Genesis,1,1,5,"And God called the light Day, and the darkness...","And God called the light Day, and the darkness..."
...,...,...,...,...,...,...,...
31097,31098,Revelation,66,22,17,"And the Spirit and the bride say, Come. And le...","And the Spirit and the bride say, Come. And le..."
31098,31099,Revelation,66,22,18,For I testify unto every man that heareth the ...,For I testify unto every man that heareth the ...
31099,31100,Revelation,66,22,19,And if any man shall take away from the words ...,And if any man shall take away from the words ...
31100,31101,Revelation,66,22,20,"¶ He which testifieth these things saith, ‹Sur...","He which testifieth these things saith, Surel..."
31101,31102,Revelation,66,22,21,The grace of our Lord Jesus Christ [be] with y...,The grace of our Lord Jesus Christ be with you...

In [6]:
genesis_by_verse_corpus = cleaned_kjv[cleaned_kjv['Book Name'] == 'Genesis']['cleaned']
genesis_by_verse_corpus

0        In the beginning God created the heaven and t...
1       And the earth was without form, and void; and ...
2        And God said, Let there be light: and there w...
3       And God saw the light, that it was good: and G...
4       And God called the light Day, and the darkness...
                              ...
1528     And Joseph dwelt in Egypt, he, and his father...
1529    And Joseph saw Ephraim's children of the third...
1530    And Joseph said unto his brethren, I die: and ...
1531    And Joseph took an oath of the children of Isr...
1532    So Joseph died, being an hundred and ten years...
Name: cleaned, Length: 1533, dtype: object

In [7]:
tfidf = TfidfVectorizer()

X = tfidf.fit_transform(genesis_by_verse_corpus)

genesis_tfidf_df = pd.DataFrame(data=X.toarray(), columns=tfidf.get_feature_names_out())
genesis_by_verse = cleaned_kjv[cleaned_kjv['Book Name'] == 'Genesis'].assign(result=genesis_tfidf_df.T.idxmax())
genesis_by_verse.head(10)

,Verse ID,Book Name,Book Number,Chapter,Verse,Text,cleaned,result
0,1,Genesis,1,1,1,¶ In the beginning God created the heaven and ...,In the beginning God created the heaven and t...,beginning
1,2,Genesis,1,1,2,"And the earth was without form, and void; and ...","And the earth was without form, and void; and ...",face
2,3,Genesis,1,1,3,"¶ And God said, Let there be light: and there ...","And God said, Let there be light: and there w...",light
3,4,Genesis,1,1,4,"And God saw the light, that [it was] good: and...","And God saw the light, that it was good: and G...",light
4,5,Genesis,1,1,5,"And God called the light Day, and the darkness...","And God called the light Day, and the darkness...",day
5,6,Genesis,1,1,6,"¶ And God said, Let there be a firmament in th...","And God said, Let there be a firmament in the...",waters
6,7,Genesis,1,1,7,"And God made the firmament, and divided the wa...","And God made the firmament, and divided the wa...",firmament
7,8,Genesis,1,1,8,And God called the firmament Heaven. And the e...,And God called the firmament Heaven. And the e...,firmament
8,9,Genesis,1,1,9,"¶ And God said, Let the waters under the heave...","And God said, Let the waters under the heaven...",let
9,10,Genesis,1,1,10,And God called the dry [land] Earth; and the g...,And God called the dry land Earth; and the gat...,called

In [8]:
genesis_by_verse[genesis_by_verse['Chapter']==39]

,Verse ID,Book Name,Book Number,Chapter,Verse,Text,cleaned,result
1150,1151,Genesis,1,39,1,¶ And Joseph was brought down to Egypt; and Po...,And Joseph was brought down to Egypt; and Pot...,down
1151,1152,Genesis,1,39,2,"And the LORD was with Joseph, and he was a pro...","And the LORD was with Joseph, and he was a pro...",was
1152,1153,Genesis,1,39,3,And his master saw that the LORD [was] with hi...,"And his master saw that the LORD was with him,...",that
1153,1154,Genesis,1,39,4,"And Joseph found grace in his sight, and he se...","And Joseph found grace in his sight, and he se...",he
1154,1155,Genesis,1,39,5,And it came to pass from the time [that] he ha...,And it came to pass from the time that he had ...,house
1155,1156,Genesis,1,39,6,And he left all that he had in Joseph's hand; ...,And he left all that he had in Joseph's hand; ...,he
1156,1157,Genesis,1,39,7,"¶ And it came to pass after these things, that...","And it came to pass after these things, that ...",cast
1157,1158,Genesis,1,39,8,"But he refused, and said unto his master's wif...","But he refused, and said unto his master's wif...",master
1158,1159,Genesis,1,39,9,[There is] none greater in this house than I; ...,There is none greater in this house than I; ne...,wickedness
1159,1160,Genesis,1,39,10,"And it came to pass, as she spake to Joseph da...","And it came to pass, as she spake to Joseph da...",her
1160,1161,Genesis,1,39,11,"And it came to pass about this time, that [Jos...","And it came to pass about this time, that Jose...",house
1161,1162,Genesis,1,39,12,"And she caught him by his garment, saying, Lie...","And she caught him by his garment, saying, Lie...",garment
1162,1163,Genesis,1,39,13,"¶ And it came to pass, when she saw that he ha...","And it came to pass, when she saw that he had...",garment
1163,1164,Genesis,1,39,14,"That she called unto the men of her house, and...","That she called unto the men of her house, and...",unto
1164,1165,Genesis,1,39,15,"And it came to pass, when he heard that I lift...","And it came to pass, when he heard that I lift...",got
1165,1166,Genesis,1,39,16,"And she laid up his garment by her, until his ...","And she laid up his garment by her, until his ...",home
1166,1167,Genesis,1,39,17,And she spake unto him according to these word...,And she spake unto him according to these word...,mock
1167,1168,Genesis,1,39,18,"And it came to pass, as I lifted up my voice a...","And it came to pass, as I lifted up my voice a...",cried
1168,1169,Genesis,1,39,19,"¶ And it came to pass, when his master heard t...","And it came to pass, when his master heard th...",kindled
1169,1170,Genesis,1,39,20,"And Joseph's master took him, and put him into...","And Joseph's master took him, and put him into...",prison
1170,1171,Genesis,1,39,21,"But the LORD was with Joseph, and shewed him m...","But the LORD was with Joseph, and shewed him m...",favour
1171,1172,Genesis,1,39,22,And the keeper of the prison committed to Jose...,And the keeper of the prison committed to Jose...,prison
1172,1173,Genesis,1,39,23,The keeper of the prison looked not to any thi...,The keeper of the prison looked not to any thi...,prosper

In [9]:
bible_by_chapter = cleaned_kjv.groupby(
    ['Book Number', 'Book Name', 'Chapter']
)[['Book Number', 'Book Name', 'Chapter', 'cleaned']].apply(lambda x: x['cleaned'].str.cat(sep=' ')).to_frame()
bible_by_chapter = bible_by_chapter.rename(columns={0:'Text'})
bible_by_chapter

                                                                             Text
Book Number Book Name  Chapter
1           Genesis    1         In the beginning God created the heaven and t...
                       2         Thus the heavens and the earth were finished,...
                       3         Now the serpent was more subtil than any beas...
                       4         And Adam knew Eve his wife; and she conceived...
                       5         This is the book of the generations of Adam. ...
...                                                                           ...
66          Revelation 18        And after these things I saw another angel co...
                       19        And after these things I heard a great voice ...
                       20        And I saw an angel come down from heaven, hav...
                       21        And I saw a new heaven and a new earth: for t...
                       22        And he shewed me a pure river of water of lif...

[1189 rows x 1 columns]

In [10]:
genesis_by_chapter = bible_by_chapter[bible_by_chapter.index.get_level_values(0) == 1].reset_index()
genesis_by_chapter

,Book Number,Book Name,Chapter,Text
0,1,Genesis,1,In the beginning God created the heaven and t...
1,1,Genesis,2,"Thus the heavens and the earth were finished,..."
2,1,Genesis,3,Now the serpent was more subtil than any beas...
3,1,Genesis,4,And Adam knew Eve his wife; and she conceived...
4,1,Genesis,5,This is the book of the generations of Adam. ...
5,1,Genesis,6,"And it came to pass, when men began to multip..."
6,1,Genesis,7,"And the LORD said unto Noah, Come thou and al..."
7,1,Genesis,8,"And God remembered Noah, and every living thi..."
8,1,Genesis,9,"And God blessed Noah and his sons, and said u..."
9,1,Genesis,10,Now these are the generations of the sons of ...
10,1,Genesis,11,"And the whole earth was of one language, and ..."
11,1,Genesis,12,"Now the LORD had said unto Abram, Get thee ou..."
12,1,Genesis,13,"And Abram went up out of Egypt, he, and his w..."
13,1,Genesis,14,And it came to pass in the days of Amraphel k...
14,1,Genesis,15,After these things the word of the LORD came ...
15,1,Genesis,16,Now Sarai Abram's wife bare him no children: ...
16,1,Genesis,17,"And when Abram was ninety years old and nine,..."
17,1,Genesis,18,And the LORD appeared unto him in the plains ...
18,1,Genesis,19,And there came two angels to Sodom at even; a...
19,1,Genesis,20,And Abraham journeyed from thence toward the ...
20,1,Genesis,21,"And the LORD visited Sarah as he had said, an..."
21,1,Genesis,22,"And it came to pass after these things, that ..."
22,1,Genesis,23,And Sarah was an hundred and seven and twenty...
23,1,Genesis,24,"And Abraham was old, and well stricken in age..."
24,1,Genesis,25,"Then again Abraham took a wife, and her name ..."
25,1,Genesis,26,"And there was a famine in the land, beside th..."
26,1,Genesis,27,"And it came to pass, that when Isaac was old,..."
27,1,Genesis,28,"And Isaac called Jacob, and blessed him, and ..."
28,1,Genesis,29,"Then Jacob went on his journey, and came into..."
29,1,Genesis,30,And when Rachel saw that she bare Jacob no ch...
30,1,Genesis,31,"And he heard the words of Laban's sons, sayin..."
31,1,Genesis,32,"And Jacob went on his way, and the angels of ..."
32,1,Genesis,33,"And Jacob lifted up his eyes, and looked, and..."
33,1,Genesis,34,"And Dinah the daughter of Leah, which she bar..."
34,1,Genesis,35,"And God said unto Jacob, Arise, go up to Beth..."
35,1,Genesis,36,"Now these are the generations of Esau, who is..."
36,1,Genesis,37,And Jacob dwelt in the land wherein his fathe...
37,1,Genesis,38,"And it came to pass at that time, that Judah ..."
38,1,Genesis,39,And Joseph was brought down to Egypt; and Pot...
39,1,Genesis,40,"And it came to pass after these things, that ..."
40,1,Genesis,41,And it came to pass at the end of two full ye...
41,1,Genesis,42,Now when Jacob saw that there was corn in Egy...
42,1,Genesis,43,And the famine was sore in the land. And it c...
43,1,Genesis,44,"And he commanded the steward of his house, sa..."
44,1,Genesis,45,Then Joseph could not refrain himself before ...
45,1,Genesis,46,And Israel took his journey with all that he ...
46,1,Genesis,47,"Then Joseph came and told Pharaoh, and said, ..."
47,1,Genesis,48,"And it came to pass after these things, that ..."
48,1,Genesis,49,"And Jacob called unto his sons, and said, Gat..."
49,1,Genesis,50,"And Joseph fell upon his father's face, and w..."

In [11]:
def tfidf_convert(corpus):
    tfidf = TfidfVectorizer()

    X = tfidf.fit_transform(corpus)

    tfidf_df = pd.DataFrame(data=X.toarray(), columns=tfidf.get_feature_names_out())

    return tfidf_df.T.idxmax()

In [12]:
bible_by_chapter

                                                                             Text
Book Number Book Name  Chapter
1           Genesis    1         In the beginning God created the heaven and t...
                       2         Thus the heavens and the earth were finished,...
                       3         Now the serpent was more subtil than any beas...
                       4         And Adam knew Eve his wife; and she conceived...
                       5         This is the book of the generations of Adam. ...
...                                                                           ...
66          Revelation 18        And after these things I saw another angel co...
                       19        And after these things I heard a great voice ...
                       20        And I saw an angel come down from heaven, hav...
                       21        And I saw a new heaven and a new earth: for t...
                       22        And he shewed me a pure river of water of lif...

[1189 rows x 1 columns]

In [13]:
bible_by_chapter = bible_by_chapter.reset_index()
bible_by_chapter

,Book Number,Book Name,Chapter,Text
0,1,Genesis,1,In the beginning God created the heaven and t...
1,1,Genesis,2,"Thus the heavens and the earth were finished,..."
2,1,Genesis,3,Now the serpent was more subtil than any beas...
3,1,Genesis,4,And Adam knew Eve his wife; and she conceived...
4,1,Genesis,5,This is the book of the generations of Adam. ...
...,...,...,...,...
1184,66,Revelation,18,And after these things I saw another angel co...
1185,66,Revelation,19,And after these things I heard a great voice ...
1186,66,Revelation,20,"And I saw an angel come down from heaven, hav..."
1187,66,Revelation,21,And I saw a new heaven and a new earth: for t...
1188,66,Revelation,22,And he shewed me a pure river of water of lif...

In [14]:
bible_by_book = bible_by_chapter.groupby(
    ['Book Number', 'Book Name']
        )[['Book Number', 'Book Name', 'Text']].apply(lambda x: x['Text'].str.cat(sep=' ')).to_frame()
bible_by_book = bible_by_book.rename(columns={0:'Text'})
bible_by_book

                                                                      Text
Book Number Book Name
1           Genesis       In the beginning God created the heaven and t...
2           Exodus        Now these are the names of the children of Is...
3           Leviticus     And the LORD called unto Moses, and spake unt...
4           Numbers       And the LORD spake unto Moses in the wilderne...
5           Deuteronomy   These be the words which Moses spake unto all...
...                                                                    ...
62          1 John        That which was from the beginning, which we h...
63          2 John        The elder unto the elect lady and her childre...
64          3 John        The elder unto the wellbeloved Gaius, whom I ...
65          Jude          Jude, the servant of Jesus Christ, and brothe...
66          Revelation    The Revelation of Jesus Christ, which God gav...

[66 rows x 1 columns]

In [15]:
tfidf_convert(bible_by_book['Text'])

0     and
1     the
2     the
3     the
4     the
     ...
61    the
62    the
63    the
64    the
65    and
Length: 66, dtype: object

In [16]:
tfidf = TfidfVectorizer(analyzer='word', stop_words='english')

X = tfidf.fit_transform(bible_by_book['Text'])

tfidf_df = pd.DataFrame(data=X.toarray(), columns=tfidf.get_feature_names_out())

In [17]:
top_words = tfidf_df.apply(lambda x: list(x.sort_values(ascending=False)[:10].index), axis=1).to_frame().rename(columns={0:'Top Words'}).head()
top_words

                                           Top Words
0  [said, unto, thou, thy, jacob, joseph, thee, s...
1  [shall, moses, thou, unto, lord, shalt, aaron,...
2  [shall, offering, unto, lord, priest, ye, uncl...
3  [shall, unto, lord, offering, moses, israel, c...
4  [thy, thou, lord, shall, shalt, thee, unto, go...

In [18]:
pd.set_option('display.max_colwidth', None)
top_words

                                                                                 Top Words
0                       [said, unto, thou, thy, jacob, joseph, thee, shall, land, abraham]
1                    [shall, moses, thou, unto, lord, shalt, aaron, pharaoh, said, israel]
2                  [shall, offering, unto, lord, priest, ye, unclean, aaron, burnt, altar]
3  [shall, unto, lord, offering, moses, israel, children, congregation, aaron, tabernacle]
4                               [thy, thou, lord, shall, shalt, thee, unto, god, land, ye]

In [19]:
top_words.head(10)

                                                                                 Top Words
0                       [said, unto, thou, thy, jacob, joseph, thee, shall, land, abraham]
1                    [shall, moses, thou, unto, lord, shalt, aaron, pharaoh, said, israel]
2                  [shall, offering, unto, lord, priest, ye, unclean, aaron, burnt, altar]
3  [shall, unto, lord, offering, moses, israel, children, congregation, aaron, tabernacle]
4                               [thy, thou, lord, shall, shalt, thee, unto, god, land, ye]

In [22]:
cleaned_csv

0                                                                                                                                                                 In the beginning God created the heaven and the earth.
1                                                                         And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.
2                                                                                                                                                                 And God said, Let there be light: and there was light.
3                                                                                                                                  And God saw the light, that it was good: and God divided the light from the darkness.
4                                                                                                    And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.
                                                                                                              ...
31097                                           And the Spirit and the bride say, Come. And let him that heareth say, Come. And let him that is athirst come. And whosoever will, let him take the water of life freely.
31098                        For I testify unto every man that heareth the words of the prophecy of this book, If any man shall add unto these things, God shall add unto him the plagues that are written in this book:
31099    And if any man shall take away from the words of the book of this prophecy, God shall take away his part out of the book of life, and out of the holy city, and from the things which are written in this book.
31100                                                                                                                    He which testifieth these things saith, Surely I come quickly. Amen. Even so, come, Lord Jesus.
31101                                                                                                                                                          The grace of our Lord Jesus Christ be with you all. Amen.
Name: Text, Length: 31102, dtype: object

In [49]:
def top_10_tfidf(csv_file_path):
    
    bible_csv = pd.read_csv(csv_file_path)
    patt = r"[^\w,;:'()\s.!?]"
    cleaned_csv = kjv_csv['Text'].str.replace(patt, '', regex=True)
    bible_csv = bible_csv.assign(clean=cleaned_csv)
    bible_csv = bible_csv.groupby(
    ['Book Number', 'Book Name']
        )[['Book Number', 'Book Name', 'clean']].apply(lambda x: x['clean'].str.cat(sep=' ')).to_frame().rename(columns={0:'Text'})

    tfidf = TfidfVectorizer(analyzer='word', stop_words='english')
    X = tfidf.fit_transform(bible_csv['Text'])
    tfidf_df = pd.DataFrame(data=X.toarray(), columns=tfidf.get_feature_names_out())
    
    top_words = (tfidf_df
                 .apply(lambda x: list(x.sort_values(ascending=False)[:10].index), axis=1)
                 .to_frame()
                 .rename(columns={0:f'Top Words ({csv_file_path[5:-4].upper()})'}))
    return top_words

In [50]:
test_csv = 'data/kjv.csv'
top_10_tfidf(test_csv)

                                                                            Top Words (KJV)
0                        [said, unto, thou, thy, jacob, joseph, thee, shall, land, abraham]
1                     [shall, moses, thou, unto, lord, shalt, aaron, pharaoh, said, israel]
2                   [shall, offering, unto, lord, priest, ye, unclean, aaron, burnt, altar]
3   [shall, unto, lord, offering, moses, israel, children, congregation, aaron, tabernacle]
4                                [thy, thou, lord, shall, shalt, thee, unto, god, land, ye]
..                                                                                      ...
61                                [god, love, world, ye, know, hath, son, sin, jesus, unto]
62               [lady, christ, truth, doctrine, speed, elect, love, unto, abideth, father]
63      [truth, thou, church, doeth, thee, beloved, record, friends, forbiddeth, malicious]
64             [ungodly, christ, jesus, unto, lord, reserved, lusts, god, beloved, eternal]
65                      [unto, angel, god, shall, earth, seven, beast, great, throne, lamb]

[66 rows x 1 columns]